version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"

    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

    depends_on:
      - mongo

  mongo:

    image: mongo:7

    ports:

      - "27017:27017"

